### ISSUE TITLE
Suggestion of information to add in different sections

### ISSUE THREAD

**Issue by CaroleSinou** [gbif/doc-openrefine-guide#19]
* __Section 1__ (https://docs.gbif-uat.org/openrefine-guide/1.0/es/#carga-de-datos-y-creaci%C3%B3n-de-un-proyecto)

   - Mention that when creating a project and uploading data, everything is done locally, and that nothing is uploaded online even if we use an Internet navigator.
   - Add information about the possibility to [increase the memory allocated to Open Refine](https://github.com/OpenRefine/OpenRefine/wiki/FAQ-Allocate-More-Memory)
   - Add information about the possibility to add [extensions](https://openrefine.org/download.html). 

* __Section 2.2__ (https://docs.gbif-uat.org/openrefine-guide/1.0/es/#facetas-y-espacios-en-blanco)

   - Mention that it is possible to select multiple values in the facets (by selecting 'include'), in order to visualize or modify several values at once.
   - Possibility to do a facet by blank, in order to find rows with missing values.
   - Possibility to use the 'invert' function in a facet in order to select the opposite set of values. Really practical when we need to select a large set of values but some.

* __Section 2.3.1 (or anywhere else suited)__ (https://docs.gbif-uat.org/openrefine-guide/1.0/es/#filtros-simples)

   - Possibility to reuse GREL expression previously used. See Figure 29, 'Historial'

* __Section 4.1.3__ (https://docs.gbif-uat.org/openrefine-guide/1.0/es/#limpieza-de-fechas-utilizando-canadensys-date-parsing)

   - Modify link to Canadensys date parser for https://data.canadensys.net/tools/dates (from http to https). URL is currently redirected to https.
   - When all dates have the __same format__, it is quicker to use a transformation with a GREL expression like: value.toDate("Format_of_the_Date").toString("yyyy-MM-dd") rather than using the Canadensys API

Note: you've done an amazing work! Thank you!

**Comment by camiplata** [comment]
+1 to 

> _"Mention that when creating a project and uploading data, everything is done locally, and that nothing is uploaded online even if we use an Internet navigator"_ 

Similarly it can be mention that by uploading a file to Open Refine, the program makes a copy, thus the original local document is not modified.

This 

> _"Add information about the possibility to increase the memory allocated to Open Refine"_ 

is key especially for [section 4](http://mb.gbif.org/documents/doc-openrefine-guide/es/#_consultas_a_servicios_externos) for using external servicies and apis, both internet connection and RAM are important

**Comment by pzermoglio** [comment]
Thanks so much @CaroleSinou and @camiplata for the excellent comments & suggestions!

- **Section 1** (https://docs.gbif-uat.org/openrefine-guide/1.0/es/#carga-de-datos-y-creaci%C3%B3n-de-un-proyecto)
- [x] Mention that when creating a project and uploading data, everything is done locally, and that nothing is uploaded online even if we use an Internet navigator.
  - added Info box for local treatment (see it after Fig 1)
- [x] Similarly it can be mention that by uploading a file to Open Refine, the program makes a copy, thus the original local document is not modified.
   - added Info box for copy of original file (see under "Paso 3).
- [x] Add information about the possibility to increase the memory allocated to Open Refine
  - added subsection under section 1, "1.3. Asignar suficientes recursos al programa". Just mentions the memory issue and points to the OR user manual for how to increase it.
- [x] Add information about the possibility to add extensions.
  - added comments in the Appendix (Apéndice), where installation instructions are given.

- **Section 2.2** (https://docs.gbif-uat.org/openrefine-guide/1.0/es/#facetas-y-espacios-en-blanco)
  - all included in new subsection: [2.2.3: Inclusión y exclusión de registros usando facetas](https://docs.gbif-uat.org/openrefine-guide/1.0/es/#inclusi%C3%B3n-y-exclusi%C3%B3n-de-registros-usando-facetas), 1 subtitle for each case there.
- [x] Mention that it is possible to select multiple values in the facets (by selecting 'include'), in order to visualize or modify several values at once.
- [x] Possibility to do a facet by blank, in order to find rows with missing values.
- [x] Possibility to use the 'invert' function in a facet in order to select the opposite set of values. Really practical when we need to select a large set of values but some.

- **Section 2.3.1** (or anywhere else suited) (https://docs.gbif-uat.org/openrefine-guide/1.0/es/#filtros-simples)
- [x] Possibility to reuse GREL expression previously used. See Figure 29, 'Historial'
    - See also https://github.com/gbif/doc-openrefine-guide/issues/25
    - Added new subsection [2.5.4. Reutilizar expresiones regulares](https://docs.gbif-uat.org/openrefine-guide/1.0/es/#reutilizar-expresiones-regulares)

- **Section 4.1.3** (https://docs.gbif-uat.org/openrefine-guide/1.0/es/#limpieza-de-fechas-utilizando-canadensys-date-parsing)
- [x] Modify link to Canadensys date parser for https://data.canadensys.net/tools/dates (from http to https). URL is currently redirected to https.
  - link to Canadensys updated.
- [x] When all dates have the same format, it is quicker to use a transformation with a GREL expression like: value.toDate("Format_of_the_Date").toString("yyyy-MM-dd") rather than using the Canadensys API
   - added Info box at the bottom to explain how to use GREL to transform dates with same format (see bottom of section).

**Comment by pzermoglio** [comment]
All topics suggested in the original issue have been addressed by either modifying or adding new content to the Guide.
Closing issue.
