### ISSUE TITLE
Resize images

### ISSUE THREAD

**Issue by pzermoglio** [gbif/doc-openrefine-guide#32]
@MattBlissett, @kcopas 
I'd like to resize some of the images in the Guide, as they currently look awkward when rendering both as as html and pdf. (E.g., Fig 5 looks extremely large, disproportionate compared to other figures).
Before I get my hands in it -not knowing well what I'm doing- is there an easy way to rescale?
Thanks!

**Comment by kcopas** [comment]
@MattBlissett will have a more sensible of making changes to anything on an automated level. If we're talking about one-off changes, that would obvs be easy enough in photoshop with a list of targets.

**Comment by pzermoglio** [comment]
I thought about doing it manually with each file, but thinking ahead, for eg translations, if we wanted to replace images with their EN versions, it would have to be dealt with again, and again...?

**Comment by MattBlissett** [comment]
The default is to scale the images to the full width of the text, which seems to work OK on the larger images, but not the smaller ones.

I've set all the images to a maximum of their display width, in pixels.  This is done by adding a width like so:

```adoc
image::img/es.figure-05.jpg[Figura 5,width=471,align=center]
```

To translate to English, we'll need a new screenshot (e.g. `img/en.figure-05.jpg`) and the translator can then change the image as part of the translation work:

```adoc
image::img/en.figure-05.jpg[Figure 5,width=471,align=center]
```

Where the image doesn't need to change (e.g. 51, 56, 57, 58) then there will be no need to change the image link, just the "Figure 51" caption.

PS images like https://docs.gbif-uat.org/openrefine-guide/1.0/img/es.figure-51.jpg are fuzzy because they have been saved as JPG (i.e. photograph format).  Saving as PNG would keep the best quality.

**Comment by pzermoglio** [comment]
Thank you @MattBlissett !!
We've played with sizes now and everything seems to be looking fine :)
Closing this issue.
